#! python3
# How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 
# and 2 ≤ b ≤ 100?

st = set([])

for a in range(2, 101):
    for b in range(2, 101):
        # print(a**b)
        st.add(a**b)

print(len(st))
