#! python3
# Triangle, pentagonal, and hexagonal numbers are generated by the following 
# formulae:

# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.


def hexgen():
    n = 1
    while True:
        yield n * (2 * n - 1)
        n += 1
        

tri = set([n * (n + 1) / 2 for n in range(10**5)])
pent = set([n * (3 * n - 1) / 2 for n in range(10**5)])

for n in hexgen():
    print(n)
    if n in tri and n in pent:
        inp = input(f"Answer is {n}")
    